spring.application.name=security
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=auth
spring.data.mongodb.uri=mongodb+srv://HomiAdmin:FYTf5LuWQK4TRAk4@homidatabase.1h3xc.mongodb.net/?retryWrites=true&w=majority&appName=HomiDatabase

jwt.secret=iohj1retgy0u89340i9j3t45jh24213tui012i414i2bh590hm213h98m232as
jwt.expirationMs=36000000