spring.application.name=security
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=auth

jwt.secret=iohj1retgy0u89340i9j3t45jh24213tui012i414i2bh590hm213h98m232as
jwt.expirationMs=36000000