spring.application.name=security
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=auth

jwt.secret=afasehfisehfosndfejndfeswljsfeow6njehwbewios4ngvhtrwglp4rkledk
jwt.expirationMs=36000000