blank_issues_enabled: false
contact_links:
  - name: 👀💻Kanban Board Issue Template👏🤙🏻g
    url: https://github.com/Leo-J-Skola/Backend_Grupp/issues/new?template=kanban_issue_template.md
    about: Use this template for issues in the Kanban board.
